/**
 * High-level goals the deliberative model may choose.
 * Execution still belongs to the deterministic planner and verified skills.
 */
export const GOALS = [
  "gather_food",
  "gather_wood",
  "mine_stone",
  "craft_tools",
  "build_shelter",
  "contribute_to_project",
  "help_citizen",
  "assist_citizen",
  "deposit",
  "use_storage",
  "rest",
  "explore",
  "defend",
  "seek_safety",
  "socialize",
  "reconsider",
] as const;

export type Goal = (typeof GOALS)[number];

export const GOAL_SET = new Set<string>(GOALS);

/** Related phrasing only. Never map gather_food → gather_wood. */
export const GOAL_ALIASES: Record<string, Goal> = {
  gatherwood: "gather_wood",
  gatherlogs: "gather_wood",
  chop_wood: "gather_wood",
  chop_trees: "gather_wood",
  get_wood: "gather_wood",
  gatherfood: "gather_food",
  get_food: "gather_food",
  hunt: "gather_food",
  minestone: "mine_stone",
  mine: "mine_stone",
  get_stone: "mine_stone",
  crafttools: "craft_tools",
  make_tools: "craft_tools",
  help: "assist_citizen",
  helpcitizen: "assist_citizen",
  assist: "assist_citizen",
  assistcitizen: "assist_citizen",
  deposit_items: "use_storage",
  store_items: "use_storage",
  put_away: "use_storage",
  use_chest: "use_storage",
  flee: "seek_safety",
  run: "seek_safety",
  survive: "seek_safety",
  hide: "seek_safety",
  talk: "socialize",
  chat: "socialize",
  converse: "socialize",
  idle: "rest",
  wait: "rest",
  sleep: "rest",
  think: "reconsider",
  rethink: "reconsider",
  pause: "reconsider",
  work_on_project: "contribute_to_project",
  join_project: "contribute_to_project",
  build_project: "contribute_to_project",
};

export const PRIVILEGED_FIELDS = new Set([
  "chain_of_thought",
  "chainofthought",
  "thinking",
  "thought",
  "cot",
  "hidden",
  "privilege",
  "tools",
  "tool_calls",
  "toolcalls",
  "execute",
  "shell",
  "sql",
  "database",
  "worldfact",
  "world_fact",
  "claimedaction",
  "claimed_action",
  "giveitem",
  "give_item",
  "spawn",
  "teleport",
  "setblock",
  "set_block",
  "inventoryadd",
  "kill",
  "command",
  "mutateworld",
]);
